route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    # email_configs:
    #   - smarthost: 'smtp-mail.outlook.com:587'
    #     auth_username: 
    #     auth_password: 
    #     from: 
    #     to: 
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
