route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'stagent9@gmail.com'
        auth_password: 'vukm crrf twby lchy'
        from: 'stagent9@gmail.com'
        to: 'your_email_here@gmail.com'