global:
  scrape_interval: 10s #Data collection interval
  evaluation_interval: 10s #Rule discovery interval
  scrape_timeout: 8s #Timeout period for collecting data



scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: 
    - localhost:9090

#Store nqmcpu address, prom will periodically fetch data from nqmcpu.
- job_name: node
  static_configs:
  - targets: 
    - localhost:9100
