global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 8s
scrape_configs:
- job_name: 'node_exporter'
  static_configs:
    - targets: 
        - node-exporter:9100
        - localhost:9100
- job_name: 'python_exporter'
  static_configs:
    - targets:
        - exporter:8000
        - localhost:8000
        - 20.107.240.171:8000   # target-1
  file_sd_configs:
    - files:
      - 'sd/azure_targets.json'