version: '3.8'

services:
  exporter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.python_exporter
    ports:
      - "8000:8000"
    volumes:
      - ../exporter:/usr/src/app/exporter
    working_dir: /usr/src/app
    command: python3 -u start_exporter.py
    networks:
      - systel-subnet

  node-exporter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node_exporter
    ports:
      - "9100:9100"
      - "80:80"
    networks:
      - systel-subnet

  grafana:
    image: grafana/grafana:10.3.3
    ports:
      - "3000:3000"
    volumes:
      - ../grafana/conf:/etc/grafana/conf
      - ../grafana/conf/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../grafana/conf/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../scripts/init-grafana.sh:/etc/grafana/init-grafana.sh
      - grafana-data:/var/lib/grafana
    networks:
      - systel-subnet

  prometheus:
    image: prom/prometheus:v2.45.3
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    networks:
      - systel-subnet

  grafana-sync-script:
    image: python:3.9
    environment:
      GRAFANA_SYNC_API: ${GRAFANA_SYNC_API}
      GRAFANA_LOCAL_API_URI: "http://grafana:3000/api"
    volumes:
      #- ../grafana/conf/provisioning/dashboards:/usr/src/app/grafana/conf/provisioning/dashboards
      - ../grafana/conf/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../scripts/export_dashboards.py:/usr/src/app/export_dashboards.py
    command: /bin/sh -c "pip install requests python-dotenv && python /usr/src/app/export_dashboards.py"
    depends_on:
      - grafana
    networks:
      - systel-subnet

volumes:
  prometheus-data:
  grafana-data:

networks:
  systel-subnet: